version: '3.7'
services:
  flights:
    build: .
    # image: flights
    restart: always
    # command: bin/wait_for_it.sh python api/app.py
    env_file: .env
    environment:
      - DIRECT_REDIS=1
      - FLASK_ENV=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/flights
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./postgres-data:/var/lib/postgresql/data

  beat_scheduler:
    build: .
    # image: flights
    restart: always
    working_dir: /flights/notifier
    command: bash ../bin/wait_for_it.sh celery -A notify beat -l info
    env_file: .env
    volumes:
      - ./:/flights
    depends_on:
      - postgres
      - redis

  notifier:
    build: .
    # image: flights
    restart: always
    working_dir: /flights/notifier
    command: bash ../bin/wait_for_it.sh celery -A notify worker -l info
    env_file: .env
    volumes:
      - ./:/flights
    depends_on:
      - postgres
      - redis
      - beat_scheduler

  redis:
    image: redis:3.2.5-alpine
    ports:
      - "6379:6379"
