version: '3.7'
services:
  flights:
    # build: .
    image: flights
    environment:
      - DIRECT_REDIS=1
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/flights
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2.5-alpine
    ports:
      - "6379:6379"
